title: Speak For Me
email: info@speakforme.in
description: >
  Speak for Me
baseurl: ""
url: "https://speakforme.in"
twitter_username: speakforme
github_username:  speakforme
thumbnail: /public/thumbnail.png
# Build settings
markdown: kramdown
google_analytics: UA-82421266-2
languages:
  - en
  - ta
  - hi
  - gu
  - bn
  - kn
  - ml
  - mr
  - pb
  - te
default_lang: en
exclude_from_localization:
  - pages
  - .bundle
  - .git
  - .sass-cache
  - _data
  - _includes
  - _layouts
  - _locales
  - _petitions
  - _sass
  - _scripts
  - _site
  - config
  - dist
  - node_modules
  - public
  - src
  - vendor
  - _headers
  - _redirects
  - favicon.ico
  - humans.txt
parallel_localization: true
exclude:
  - _locales
  - _scripts
  - src
  - config
  - package.json
  - package-lock.json
  - HACKING.md
  - Gulpfile.js
  - Gemfile.lock
  - Gemfile
  - CNAME
  - vendor
# https://www.netlify.com/docs/redirects/
include:
  - _redirects
  - _headers
